apiVersion: apps/v1
kind: Deployment 
metadata:
  name: auth-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec: 
      containers:
        - name: auth-app-container
          image: supermendax95/kube-demo-auth:v1
          imagePullPolicy: IfNotPresent
          