apiVersion: apps/v1 
kind: Deployment
metadata:
  name: story-app-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story-app
          image: supermendax95/story-app-data-demo:v2
          volumeMounts: 
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate


---

apiVersion: v1 
kind: Service
metadata:
  name: story-app-service 
spec:
  selector:
    app: story-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000 
  type: LoadBalancer
