apiVersion: v1
kind: Service
metadata:
  name: sortiz-second-app-service
spec:
  selector: 
    app: sortiz-second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer