version: '3.8'
services:
  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=123
    networks:
      - redmine-network 
    restart: always
  postgres: 
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=redmine
    volumes:
      #- $PWD/data:/var/lib/postgresql/data
      - postgres:/var/lib/postgresql/data
    networks:
      - redmine-network
volumes:
  postgres:
networks:
  redmine-network: 

