# use the base python image
FROM python 

# set /app as the working directory
WORKDIR /app 

# copy all the content in the local directory to /app
COPY . /app

# execute the app with the python executable
CMD ["python", "rng.py"]
