# creates the userapp deployment and service
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: users-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app 
    spec:
      containers:
        - name: users-app-container
          image: supermendax95/kub-demo-users:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: AUTH_ADDRESS 
              #value: localhost - localhost when the communication is inside the same pod - ip address of the service when the communication is between pods
              valueFrom:
                configMapKeyRef:
                  name: networking-env
                  key: auth-ip-address

--- 

apiVersion: v1 
kind: Service 
metadata:
  name: users-app-service
spec:
  selector: 
    app: users-app
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080 
  type: LoadBalancer


  