apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: tasks-app-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: tasks-app
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
        - name: tasks-app-container
          image: supermendax95/kub-demo-tasks:v1
          imagePullPolicy: IfNotPresent
          env: 
            - name: AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: networking-env
                  key: auth-service-address
            - name: TASKS_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: networking-env
                  key: tasks-folder

--- 

apiVersion: v1
kind: Service
metadata: 
  name: tasks-app-service
spec:
  selector: 
    app: tasks-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer